CREATE TABLE completed_request
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address      VARCHAR(15),
    source_text     TEXT,
    translated_text TEXT,
    CONSTRAINT pk_completed_request PRIMARY KEY (id)
);